before_script:
  #中文乱码问题
  - chcp 65001
  - cd src

# 执行的 job 
stages:
  - test
  - deploy

# 校验代码
test:
  stage: test
  # 将会执行的脚本
  script:
    - dotnet restore
    - dotnet build
  # 哪个分支会执行
  only:
    - master
    #runner 注册时的 tag，这里指会触发的 runner
  tags:
    - deploy

# 部署
deploy:
  stage: deploy
  # 将会执行的脚本
  script:
    # 声明一个变量保存当前时间，用作备份数据文件夹名称
    - $datetime=Get-Date -Format 'yyyy-MM-dd-HH-mm'
    # 编译打包项目
    - dotnet publish -c release -r win81-x64
    # 进入编译好的项目目录
    - cd $env:ProjectName\bin\Release\netcoreapp2.2\win81-x64\
    # 停止 IIS 对应站点
    - C:\Windows\System32\inetsrv\appcmd.exe stop site $env:WebSiteName
    # 停止进程池
    - C:\Windows\System32\inetsrv\appcmd.exe stop apppool /apppool.name:"$env:WebSiteName"
    # 备份原有项目文件，项目名_当前时间
    - cp "$env:WebSitePath" "$env:WebSitePath$datetime" -Recurse
    # 删除原有站点
    - del "$env:WebSitePath" -Recurse
    - cp "publish" "$env:WebSitePath" -Recurse
    # 启动进程池
    - C:\Windows\System32\inetsrv\appcmd.exe start apppool /apppool.name:"$env:WebSiteName"
    # 启动 IIS 站点
    - C:\Windows\System32\inetsrv\appcmd.exe start site $env:WebSiteName
  
  # 哪个分支会执行
  only:
    - master
  #runner 注册时的 tag，这里指会触发的 runner
  tags:
    - deploy
